diff.astextplain.textconv=astextplain
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=true
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=EWANE EWANE
user.email=ewane@softronic-cm.com
safe.directory=D:/Projects/Sources/repos/BrainOApprob
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
gitflow.branch.master=main
gitflow.branch.develop=develop
gitflow.prefix.feature=feature/
gitflow.prefix.bugfix=bf
gitflow.prefix.release=rls
gitflow.prefix.hotfix=hf
gitflow.prefix.support=support/
gitflow.prefix.versiontag=v
gitflow.path.hooks=C:/swin/s/ang/.git/hooks
user.name=ewane ewane
user.email=ewane.ewane@hotmail.com
remote.origin.url=git@github.com:EWE-2/lj_foundation.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
branch.develop.remote=origin
branch.develop.merge=refs/heads/develop
